# Generated by Django 4.1.4 on 2022-12-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address1',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
